name: Test

on:
  push:
    branches: 
      - master
    paths: 
      - '.github/workflows/test-1.yml'

jobs:

  build:
    
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
      
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d
          sudo apt-get update
          sudo apt-get -y install bc build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          wget -O - https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | bash
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk
          git config --global user.name "kongfl888"
          git config --global user.email "kongfl888@outlook.com"
          
      - name: Install Repo
        run: |
          git clone https://github.com/friendlyarm/repo
          sudo cp repo/repo /usr/bin/

      - name: Init Source
        run: |
          mkdir friendlywrt-rk3328
          cd friendlywrt-rk3328
          repo init -u https://github.com/kongfl888/friendlywrt_manifests -b lede -m rk3328.xml --repo-url=https://github.com/friendlyarm/repo  --no-clone-bundle
          #rm -f .repo/manifests/rk3328.xml
          #cp ../JUNK/rk3328.xml .repo/manifests/rk3328.xml
          repo sync -c  --no-clone-bundle

      - name: Patch For R2S
        run: |
          . ./scripts/patch_for_r2s.sh

      - name: Mods
        run: |
          cd friendlywrt-rk3328
          #. ../remove_unused_config.sh
          #. ../patch_dosth.sh
          #sed -i 's/CONFIG_BPFILTER=y/CONFIG_BPFILTER=n/' kernel/arch/arm64/configs/nanopi-r2_linux_defconfig
          sed -i 's/dnsmasq /dnsmasq-full /' friendlywrt/include/target.mk
          [ -f configs/config_rk3328 ] && sed -i '/adblock/d;/docker/d;/DOCKER/d;/mwan3/d;/OPENVPN/d;/openvpn/d;' configs/config_rk3328
          sed -i '/luci-app/d;/kmod-/d;/_lib/d;/luci-i18n/d' configs/config_rk3328
          echo "CONFIG_PACKAGE_libexpat=y" >> configs/config_rk3328
          cd friendlywrt
          mv ../../scripts/one_time_init.sh package/base-files/files/usr/bin && sed -i '/exit/i\/bin/sh /usr/bin/one_time_init.sh 24 &' package/base-files/files/etc/rc.local
          mv ../../scripts/flash_rom.sh package/base-files/files/root/flash_rom.sh && chmod +x package/base-files/files/root/flash_rom.sh
          . ../../scripts/buildtime.sh
          #rm -f ./feeds.conf.default && wget -O ./feeds.conf.default https://raw.githubusercontent.com/openwrt/openwrt/master/feeds.conf.default
          # for temporary,TRY to fix libexpat complie error
          #sed -i '/src-git packages/d' ./feeds.conf.default && echo "src-git packages https://github.com/kongfl888/packages.git" >> ./feeds.conf.default
          sed -i 's,mkdir -p $(1)\/usr\/bin,rm -rf $(1)\/usr\/bin \&\& mkdir -p $(1)\/usr\/bin \|\| mkdir -p $(1)\/usr\/bin,g' package/base-files/Makefile

      - name: Clean Feeds
        run: |
          cd friendlywrt-rk3328/friendlywrt
          ./scripts/feeds clean -a

      - name: Update Feeds
        run: |
          cd friendlywrt-rk3328/friendlywrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build FriendlyWrt
        run: |
          cd friendlywrt-rk3328
          . ../scripts/rename_sdimg.sh 24 || echo ""
          sed -i 's/set -eu/set -u/' scripts/mk-friendlywrt.sh
          ./build.sh nanopi_r2s.mk

      - name: Zip Files
        run: |
          gzip friendlywrt-rk3328/out/*.img
      - name: Assemble Artifact
        id: assemble_artifact
        run: |
          rm -rf ./r2srom/
          mkdir -p ./r2srom/
          mv friendlywrt-rk3328/out/*img* ./r2srom/
          cp friendlywrt-rk3328/friendlywrt/.config ./r2srom/
          cd ./r2srom/
          sha256sum *img* > sha256sum.txt
          cd ..
          mkdir -p ./ipks/
          cp friendlywrt-rk3328/friendlywrt/.config ./ipks/
          . ./scripts/copyipk.sh
          cd ./ipks/
          sha256sum *ipk > packages.sha256
          cd ..
          cp ./README.txt ./r2srom/
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: r2srom
          path: ./r2srom/
